rails-longest-word-game/config/routes.rb
Rails.application.routes.draw do
  get 'game', to: "game#game"

  get 'score', to: "game#score"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails-longest-word-game/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-longest-word-game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-longest-word-game/app/controllers/game_controller.rb
require "open-uri"
require "nokogiri"

class GameController < ApplicationController
  def game
    @grid = (Array.new(7) { ('A'..'Z').to_a.sample }).join
    @start_time = Time.now
  end

  def score
    @word = params[:longest_word]
    @end_time = Time.now
    @total_time = @end_time - Time.parse(params[:start_time])
    @grid = params[:grid]
    @compute_score = score_and_message(@word, @grid, @total_time)
  end

  private

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    score_and_message = score_and_message(attempt, grid, result[:time])
    result[:score] = score_and_message.first
    result[:message] = score_and_message.last

    result
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end

end

rails-longest-word-game/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-longest-word-game/app/helpers/game_helper.rb
module GameHelper
end

rails-longest-word-game/app/views/game/game.html.erb
<h1>Game#game</h1>
<p>Let's play a game!</p>
<p>Please type the longest word you can find among these letters!</p>

<p class = "grid"><%= @grid %> </>

<p> <%= @start_time %> </p>

<h3>Type your answer when ready!</h3>
<form action="/score" method="get">
  <label for="word"></label>
  <input type="text" id="word" name="longest_word" placeholder="your answer...">
  <input type="hidden" id="start_time" name="start_time" value= "<%= @start_time %>">
  <input type="hidden" id="grid" name="grid" value= "<%= @grid %>">
  <input type="submit">
</form>

rails-longest-word-game/app/views/game/score.html.erb
<h1>Game#score</h1>
<p>Your word: <%= @word %> </p>

<p>Time taken to answer: <%= @total_time %> seconds</p>

<p>Your score: <%= @compute_score.first %></p>

<p> <%= @compute_score.last.capitalize %></p>

<%= link_to "Play again", game_path %>

<!-- Your word: ax
Time Taken to answer: 9.664008
Your score: 1.6778664
Message: well done -->

rails-longest-word-game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>